# conda environment for rascil
#
# Create it using:
#
#   conda env create -f environment.yml 
#   conda activate rascil_env
#   conda config --env --prepend channels astropy
#
name: rascil_env
channels:
  - defaults
  - conda-forge
dependencies:
  - astropy
  - astroplan
  - numpy
  - scipy
  - scikit-image
  - matplotlib<3.1.3
  - h5py
  - dask
  - distributed
  - paramiko
  - python-graphviz
  - bokeh
  - jupyter
  - sphinx
  - sphinx_rtd_theme
  - photutils
  - reproject
  - numba
  - pip
  - python-casacore
  - pip:
    - seqfile
    - aotools

