"""
Functions for visibility coalescence and decoalescence.
"""
from rascil.processing_components.visibility.coalesce import coalesce_visibility
from rascil.processing_components.visibility.coalesce import convert_blockvisibility_to_visibility
from rascil.processing_components.visibility.coalesce import decoalesce_visibility
from rascil.processing_components.visibility.coalesce import convert_visibility_to_blockvisibility