""" Visibility iterators for iterating through a BlockVisibility or Visibility.

"""
from rascil.processing_components.visibility.gather_scatter import visibility_scatter
from rascil.processing_components.visibility.gather_scatter import visibility_gather
from rascil.processing_components.visibility.gather_scatter import visibility_scatter_w
from rascil.processing_components.visibility.gather_scatter import visibility_scatter_time
from rascil.processing_components.visibility.gather_scatter import visibility_gather_w
from rascil.processing_components.visibility.gather_scatter import visibility_gather_time
from rascil.processing_components.visibility.gather_scatter import visibility_scatter_channel
from rascil.processing_components.visibility.gather_scatter import visibility_gather_channel