"""
Functions that aid testing in various ways. 
"""

from rascil.processing_components.simulation import create_test_image
from rascil.processing_components.simulation import create_test_image_from_s3
from rascil.processing_components.simulation import create_low_test_image_from_gleam
from rascil.processing_components.simulation import create_low_test_skymodel_from_gleam
from rascil.processing_components.simulation import create_low_test_skycomponents_from_gleam
from rascil.processing_components.simulation import create_test_skycomponents_from_s3
from rascil.processing_components.simulation import replicate_image
from rascil.processing_components.simulation import create_blockvisibility_iterator
from rascil.processing_components.simulation import simulate_gaintable
from rascil.processing_components.simulation import simulate_pointingtable
from rascil.processing_components.simulation import simulate_pointingtable_from_timeseries
from rascil.processing_components.simulation import ingest_unittest_visibility
from rascil.processing_components.simulation import create_unittest_components
from rascil.processing_components.simulation import create_unittest_model
from rascil.processing_components.simulation import insert_unittest_errors